### ISSUE TITLE
healPlayer in functions.php not working

### ISSUE THREAD

**Issue by nsonP** [R4Z0R49/DayZAdmin#248]
Have been trying to fix this function for a while now. The problem is that the function healPlayer in actions.php is not adding the blood type and the flag that tells if it should be visible for the player or not.

```
$db->Execute("UPDATE Character_DATA SET Medical = '[false,false,false,false,false,false,false,12000,[],[0,0],0,[0,0]]' WHERE CharacterID = ? AND Alive = 1", $CharacterID);

[false,false,false,false,false,false,false,12000,[],[0,0],0,[0,0]]
```
The new string should look like:
```
[false,false,false,false,false,false,false,12000,[],[0,0],0,"A",false,[0,0,0]]
```

A quick fix would be to just update the string with above and have a static blood type but then the players will get the same blood typ every time the function is used.

A better approach that i have been trying to implement is to copy the last original part of the string and then replace the rest with static info.

__*example:*__
```
SET @Part1 := '[false,false,false,false,false,false,false,12000,[],[0,0],0,"';
SET @Part2 :=  (SELECT substring_index(medical, ',"', -1) FROM character_dead where CharacterID = 2);
UPDATE character_dead SET Medical = @Part1+@Part2 WHERE CharacterID = 2;
UPDATE character_dead SET Medical = CONCAT(medical, '@part2') CharacterID = 2;
``` 
Its working fine as a mysql query but not together with php and adodb.
Any idea of how to fix this one?

**Comment by wriley** [comment]
I'm pretty short on time these days but this is definitely fixable. I'll try to take a look at it in the next few days.

**Comment by nsonP** [comment]
Great, tell me if i can help with anything!

**Comment by Marcuzz** [comment]
I'm uploading a fix for this in a sec

**Comment by Marcuzz** [comment]
492107d24d0820edcec9a9d9cc7112fd81581d1e

Fixed :)

**Comment by wriley** [comment]
Thanks Marcus

**Comment by R4Z0R49** [comment]
Cheers Marcuzz, Wriley

**Comment by nsonP** [comment]
Working like a charm! Tanks!

**Comment by wriley** [comment]
Closing as fixed
