### ISSUE TITLE
modules/check.php only checking players

### ISSUE THREAD

**Issue by nsonP** [R4Z0R49/DayZAdmin#249]
I have noticed that the item check function is only working for 'players' and not for tents, stashes and vehicles.

If one of you have a minute to spare it would be highly appreciated since it's a nifty tool to find suspicious players with.

**Comment by wriley** [comment]
@nsonP I found that it is not checking upgraded tents or stashes but is showing vehicles. Could you be more specific about what is not working? Thanks for the report

**Comment by nsonP** [comment]
Sorry for the delayed answer.
I found the issue and that's with the new cleanup procedure that moves all dead characters to the character_dead table. So long story short, It doesn't find unknown items that's located on dead players.

I'll test with an union and see if it works out.

**Comment by wriley** [comment]
AFAIK the Character_DEAD table is no longer used. The table SQL is still there in 1.8.5 but pCleanup no longer moves dead players

**Comment by nsonP** [comment]
We still use the character_dead since we wants to keep the statistics.
The table is still in the SQL bundle for 1.8.5, i'll check with R4Z0R if it's intentional or they just missed the procedure to move the dead character before deleting after 90 days

**Comment by wriley** [comment]
@nsonP I added a UNION in #266

**Comment by cikez** [comment]
Can we confirm if the character_dead table is still being used in 1.8.6.1 or can it be removed? Thanks.

**Comment by wriley** [comment]
@R4Z0R49 Is the Character_DEAD table deprecated? Dead characters are no longer being moved to it, is that intentional? Thanks!

**Comment by R4Z0R49** [comment]
im going to add a new cleanup system to remove dead chars over a certain age rather then moving them.

**Comment by wriley** [comment]
@R4Z0R49 OK thanks, I'll close this.
