### ISSUE TITLE
Fatal error: Call to a member function SetFetchMode() on a non-object in C:\inetpub\wwwroot\dz\db.php on line 6

### ISSUE THREAD

**Issue by cikez** [R4Z0R49/DayZAdmin#275]
Just installed this and received the following error:

Fatal error: Call to a member function SetFetchMode() on a non-object in C:\inetpub\wwwroot\dz\db.php on line 6

Am I missing something here?

Thanks.

**Comment by wriley** [comment]
That probably means something is not right with your database settings. Check your settings in config.php

**Comment by cikez** [comment]
Hmmm all the settings look correct. Anyway to further troubleshoot?

Thanks.

**Comment by wriley** [comment]
ADODB is not creating a new object for some reason. You could try moving $db->debug above the call to SetFetchMode and setting it to true. That may give more output as to why ADO is failing.

```
$db = ADONewConnection('mysqli://'.$username.':'.$password.'@'.$hostname.'/'.$dbName.'?port='.$dbport);
$db->debug = true;
$db->SetFetchMode(ADODB_FETCH_ASSOC);
$db->SetCharset('utf8');
```

**Comment by cikez** [comment]
Warning: Creating default object from empty value in C:\inetpub\wwwroot\dz\db.php on line 6

Fatal error: Call to undefined method stdClass::SetFetchMode() in C:\inetpub\wwwroot\dz\db.php on line 7

**Comment by wriley** [comment]
Unfortunately that tells us nothing. :( Maybe something is missing from PHP? Are there any clues in the PHP or web server logs?

I really should wrap that object creation in a try/catch so you might try changing db.php to this and see if any useful info shows up:
```
<?php
require_once('config.php');
require_once('adodb5/adodb.inc.php');

try {
    $db = ADONewConnection('mysqli://'.$username.':'.$password.'@'.$hostname.'/'.$dbName.'?port='.$dbport);
    $db->debug = false;
    $db->SetFetchMode(ADODB_FETCH_ASSOC);
    $db->SetCharset('utf8');
} catch (Exception $e) {
    print_r($e);
}

?>
```

**Comment by Marcuzz** [comment]
Make sure you have the mysqli extension enabled in your php.ini config file

**Comment by cikez** [comment]
@marcuzz

You are the man sir! I totally forgot to check that. That was indeed the issue. All is good now. Thanks!!
