### ISSUE TITLE
Vulnerable to SQL Injection?

### ISSUE THREAD

**Issue by cikez** [R4Z0R49/DayZAdmin#276]
I just wanted to bring this to your attention. It could possibly be vulnerable to SQL injection. Might want to look into this.

I am not pro at mySQL but from what I can see it would benefit all of us to switch the queries to PDO with prepared statements.

Thanks.

**Comment by wriley** [comment]
All mysql calls are done through adodb library using prepared statements so should be fine. Did you have a specific example where this wasn't the case?

**Comment by cikez** [comment]
No specific case, just something I came across. I do not know much about adodb. 

I did notice if you go to index.php?leaderboard&limit=101%20and%201=1 it shows a warning.

Shouldn't the code "escape" this command and say not found? Instead its showing:

Warning: Invalid argument supplied for foreach() in modules\leaderboard.php on line 54.

Thanks.

**Comment by Marcuzz** [comment]
https://github.com/R4Z0R49/DayZAdmin/blob/master/modules/leaderboard.php#L50

That was made before I knew the importance of web security and how to actually use adodb / PDO properly

**Comment by wriley** [comment]
@Marcuzz If you want to clean that up go for it. If not, I can probably get to it in the next week or so. Thanks @cikez for the report.

**Comment by cikez** [comment]
Sounds good.

No problem guys. Thanks for the quick replys.

**Comment by wriley** [comment]
Closing this with #282
