### ISSUE TITLE
Create suitable images for fences, gates, and base fires

### ISSUE THREAD

**Issue by wriley** [R4Z0R49/DayZAdmin#284]

**Comment by wriley** [comment]
Base_Fire_DZ
WoodenFence_1
WoodenFence_1_foundation
WoodenFence_1_frame
WoodenFence_2
WoodenFence_3
WoodenFence_4
WoodenFence_5
WoodenFence_6
WoodenFence_7
WoodenFence_halfpanel
WoodenFence_quarterpanel
WoodenFence_thirdpanel
WoodenGate_1
WoodenGate_2
WoodenGate_3
WoodenGate_4
WoodenGate_foundation

**Comment by nsonP** [comment]
Would you be OK with images from Oxygen?

**Comment by R4Z0R49** [comment]
dont spend too much time on them. They will change for the 2nd iteration of the fence system

**Comment by wriley** [comment]
@nsonP Yes, model images from O2 would be fine. I created this issue so we wouldn't forget to replace the placeholder images at some point.

**Comment by wriley** [comment]
@nsonP  Thanks for the images
