### ISSUE TITLE
Mission Folder Not Writable?

### ISSUE THREAD

**Issue by AutoJukebox** [R4Z0R49/DayZAdmin#293]
Hello, I was adding vehicles via mission.sqf in your panel and keeps telling me that my mission folder is not writable even tho my webuser has full access to my arma2 server...

I'm on the latest version of DayZ and DayZ Admin and i am on Windows Server 2012r2

**Comment by Marcuzz** [comment]
Make sure to the user has write permissions within the security properties of the mission folder, and that it's the same user that accesses FTP. Sometimes it's guest by default:

![Security properties](https://marcuz.eu/files/PCLY.png)

**Comment by AutoJukebox** [comment]
I hate to be dumb but what mission folder are you referring to? MPMissions?

**Comment by AutoJukebox** [comment]
Ok, Nevermind it uploaded now, But now it's saying "No Option Selected"

**Comment by Marcuzz** [comment]
You probably forgot to tick an option, and I meant the "mission" folder within DayZAdmin

**Comment by AutoJukebox** [comment]
![ss 2016-07-05 at 02 28 17](https://cloud.githubusercontent.com/assets/8949747/16595396/e0782658-42bc-11e6-96a5-0ed428c9fb3a.png)

**Comment by Marcuzz** [comment]
I don't think that error has any important meaning, check if the vehicles actually spawn

**Comment by AutoJukebox** [comment]
So i think i found the issue, The mission.sqf i extracted from my 3d editor has nothing in it....

**Comment by Marcuzz** [comment]
That is it, yeah haha. Your error means no queries were ran successfully, which is pretty obvious now that you say the file is empty

**Comment by AutoJukebox** [comment]
I added like 400 Vehicles and none of them wrote to the sqf in the mission.chernarus.pbo..... Do you know of anyway to fix that?

**Comment by Marcuzz** [comment]
I have never heard of the issue before, unfortunately

**Comment by AutoJukebox** [comment]
Hey nevermind i saved it again as a usermission and it worked. Thank for your help man!

**Comment by AutoJukebox** [comment]
No vehicles after uploading my mission.sqf it said successfully spawned but nothing is there when i load into the server
