### ISSUE TITLE
Backpack Bugs, Clothing Bug, Breathing

### ISSUE THREAD

**Issue by BikiniPotato** [R4Z0R49/DayZAdmin#294]
Hello! 

Let's Start with the Backpack bug, I don't really know how it is working but It started happening too often some days, It is just some about items are disapearing from ur backpack for no reason after logging off.
Today I logged off because had to do something and I logged in after like 15min and I noticed that everything from my backpack just disapear, Vinyl Junkie from DayZ Europa Vanilla can provide u LOGs from server what happend.

Next bug is with backpack when u put like almost empty magazines inside of ur backpack before logging off or before server restart u will get them fully, same is with the clothing when u put the magazines inside of ur backpack and then u change ur clothing from like CAMO, SOLDIER, GHILLIE to the Civilian clothing u will get FULL magazines, Probally everyone knows about it but is really anoying when people are using that game breaking bug...

Another one is with Breathing, when u are exhausted we all know ur SIGHT from the GUN is swinging around because u are tired after making some distance and u need to catch some breath so let's get to the case about it, When u are exhausted all u need to do is use clothing, from like CAMO, SOLDIER, GHILLIE to civilian clothing and ur breath will be normal and u can shoot easly..

PS. Sorry for my English, Im just trying to help u with it. I don't know if u know about that bugs but I want to share it with u, maybe u can fix it.

**Comment by R4Z0R49** [comment]
Thanks for the info, hopefully one has been fixed the others we cant do anything about with native commands within arma. Maybe someday (2.0) we might see a fix using external systems.
